routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\UserRole;

Route::group(['middleware' => 'web'], function () {

    $role[UserRole::ADMIN]      = UserRole::ADMIN;
    $role[UserRole::CITY_ADMIN] = implode('+', [UserRole::ADMIN, UserRole::CITY_ADMIN]);
    $role[UserRole::LC]         = implode('+', [$role['city_admin'], UserRole::LC]);
    $role[UserRole::REP]        = implode('+', [$role['city_admin'], UserRole::REP]);
    $role[UserRole::DRIVER]     = implode('+', [$role['city_admin'], UserRole::DRIVER]);

    Route::group(['namespace' => UserRole::ADMIN, 'middleware' => ['auth', 'authorize:'.$role[UserRole::ADMIN]]], function () {
//        $this->get('country', 'CountryController@index')->name('country');
//        $this->get('city', 'CityController@index')->name('city');
//        $this->get('city_admin', 'UserController@city_admin')->name('city_admin');
        $this->resources([
            'country'           => 'CountriesController',
            'city'              => 'CitiesController',
            'passenger-type'    => 'PassengerTypesController',
        ]);
    });



    Route::group(['namespace' => UserRole::CITY_ADMIN, 'middleware' => ['auth', 'authorize:'.$role[UserRole::CITY_ADMIN]]], function () {
        $this->get('upload-data', 'UploadController@upload_data')->name('upload-data');
        $this->post('arrival-list', 'UploadController@arrival_list')->name('arrival-list');
        $this->post('transfer-list', 'UploadController@transfer_list')->name('transfer-list');

        $this->resources([
            'user'   =>'UsersController',
            'hotel'  =>'HotelsController'
        ]);

//        $this->get('lc', 'UserController@lc')->name('lc');
//        $this->get('rep', 'UserController@lc')->name('rep');
//        $this->get('driver', 'UserController@lc')->name('driver');
//
//        $this->get('hotel', 'HotelController@index')->name('hotel');
//
//        $this->get('passenger-type', 'PassengerTypeController@index')->name('passenger-type');
//
//        $this->get('telegram', 'TelegramController@index')->name('telegram');
    });

    Route::group(['prefix' => '/', 'middleware'=>['auth']], function() {

        $this->get('dashboard', function () {
            return view('dynamic-master', ['page'=>'dashboard']);
        })->name('dashboard');

        $this->resources([
            'booking'   => 'BookingsController'
        ]);

        $this->get('logout', 'Auth\LoginController@logout')->name('logout');

    });

});
// Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
//     $this->get('upload-data', 'AdminController@upload_data')->name('upload-data');
//     $this->post('arrival-list', 'UploadController@arrival_list')->name('arrival-list');
//     $this->post('transfer-list', 'UploadController@transfer_list')->name('transfer-list');
//     $this->get('lc', 'AdminController@lc')->name('admin.lc');
// });


Route::match(['get', 'post'], '/botman', 'BotManController@handle');
Route::get('/botman/tinker', 'BotManController@tinker');

Auth::routes();

Route::get('/', function (){
    return redirect(route('login'));
});

resources/views/booking_index.blade.php
@section('content')
    <div class="row ltr">
        <div class="table-responsive">
            <table class="table table-hover table-bordered table-hover" style="border: 2px solid white">
                <thead>
                <tr>
                    <th>کد رزرو</th>
                    <th>هتل</th>
                    <th>مسافر</th>
                    <th>تاریخ رزرو</th>
                    <th>Driver No Show</th>
                    <th>LC Check Time</th>
                    <th>REP Check Time</th>
                    <th>Pickup Time</th>
                    <th>نوع مسافر</th>
                </tr>
                </thead>
                <tbody>
                @foreach($bookings as $booking)
                <?php
                $no_show = empty($booking->no_show)?'':with(new \Datetime())->setTimestamp(strtotime($booking->no_show))->format('Y-m-d H:i');
                $check_by_lc = empty($booking->check_by_lc)?'':with(new \Datetime())->setTimestamp(strtotime($booking->check_by_lc))->format('Y-m-d H:i');
                $check_by_rep = empty($booking->check_by_rep)?'':with(new \Datetime())->setTimestamp(strtotime($booking->check_by_rep))->format('Y-m-d H:i');
                $pickup_time = empty($booking->pickup_time)?'':with(new \Datetime())->setTimestamp(strtotime($booking->pickup_time))->format('Y-m-d H:i');
                $passenger_type = $booking->passenger->passengerType?$booking->passenger->passengerType->type:'مشخص نشده';
                ?>
                    <tr>
                        <td><a href="{{route('booking.show',['id'=>$booking->id])}}">{{ $booking->booking_id }}</a></td>
                        <td>{{ $booking->hotel?$booking->hotel->title:'' }}</td>
                        <td>{{ $booking->passenger->fullname() }}</td>
                        <td>{{ $booking->booking_date }}</td>
                        <td>{{ $no_show }}</td>
                        <td>{{ $check_by_lc }}</td>
                        <td>{{ $check_by_rep }}</td>
                        <td>{{ $pickup_time }}</td>
                        <td>{{ $passenger_type }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        {{ $bookings?$bookings->links():'' }}
    </div>
@stop

resources/views/booking_show.blade.php
@section('content')
<?php
    $passenger  = $booking->passenger;
    $phonenumber  = $passenger->phonenumber()->first();
    $passtype   = $passenger->passengerType;
    $hotel      = $booking->hotel;
    $city       = $hotel?$hotel->city:false;
    $checkin    = $booking->checkin;
    $checkin_airline    = $checkin->airline;
    $checkin_terminal    = $checkin->terminal;
    $checkin_supplier   = $checkin->supplier;
    $checkin_city       = $checkin->city;
    $checkin_cartype    = $checkin->cartype;
    $checkin_transfertype    = $checkin_cartype?$checkin_cartype->carTransferType:false;
    
    $checkout            = $booking->checkout;
    $checkout_airline    = $checkout->airline;
    $checkout_terminal   = $checkout->terminal;
    $checkout_supplier   = $checkout->supplier;
    $checkout_city       = $checkout->city;
    $checkout_cartype    = $checkout->cartype;
    $checkout_transfertype    = $checkout_cartype?$checkout_cartype->carTransferType:false;
    $data = [
        'کد رزرو'       => $booking->booking_id,
        'تاریخ رزرو'    => $booking->booking_date,
        'مسافر'         => $passenger?$passenger->fullname():'',
        'شماره تلفن مسافر'  => $phonenumber?$phonenumber->phonenumber:'',
        'نوع مسافر'     => $passtype?$passtype->type:'',
        'هتل'           => $hotel?$hotel->title:'',
        'شهر'           => $city?$city->title:'',
        'مرجع تامین کننده' => $booking->supplier_ref,
        'زمان تاییدیه مشاور تفریحی' => $booking->check_by_lc,
        'زمان تاییدیه نماینده' => $booking->check_by_rep,
        'زمان اعلام عدم حضور توسط راننده' => $booking->no_show,
        'زمان انتظار مسافر' => $booking->pickup_time,
        'تعداد اتاق ها' => $booking->no_of_rooms,
        'تعداد مسافران' => $booking->no_of_passengers,

        'تاریخ و زمان ورود' => $checkin->date . ' ' . $checkin->time,
        'خط هوایی ورود' => $checkin_airline?$checkin_airline->title:'',
        'تامین کننده ورود' => $checkin_supplier?$checkin_supplier->title:'',
        'شماره پرواز ورود' => $checkin->flight_no,
        'شهر مبدا' => $checkin_city?$checkin_city->title:'',
        'نوع وسیله حامل ورود' => $checkin_cartype?$checkin_cartype->type:'',
        'نوع انتقال ورود' => $checkin_transfertype?$checkin_transfertype->type:'',
        'پایانه ورود' => $checkin_terminal?$checkin_terminal->title:'',
        
        'تاریخ و زمان بازگشت' => $checkout->date . ' ' . $checkout->time,
        'خط هوایی بازگشت' => $checkout_airline?$checkout_airline->title:'',
        'تامین کننده بازگشت' => $checkout_supplier?$checkout_supplier->title:'',
        'شماره پرواز بازگشت' => $checkout->flight_no,
        'شهر بازگشت' => $checkout_city?$checkout_city->title:'',
        'نوع وسیله حامل بازگشت' => $checkout_cartype?$checkout_cartype->type:'',
        'نوع انتقال بازگشت' => $checkout_transfertype?$checkout_transfertype->type:'',
        'پایانه بازگشت' => $checkout_terminal?$checkout_terminal->title:'',

    ];
?>
@yield('edit_booking')
<div class="row">
    <div class="table-responsive">
        <table class="table table-hover table-bordered table-hover" style="border: 2px solid white">
            <thead>
            <tr>
                <th>خصیصه</th>
                <th>مقدار</th>
            </tr>
            </thead>
            <tbody>
                @foreach($data as $key => $value)
                <tr>
                    <td><strong>{{ $key }}</strong></td>
                    <td>{{ $value }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@stop

resources/views/dynamic-master.blade.php
@extends('layouts.master')

@extends('section.panel_menu')

@extends(auth()->user()->role.'.'.$page)

resources/views/tinker.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>BotMan Studio</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <style>
        body {
            font-family: "Source Sans Pro", sans-serif;
            margin: 0;
            padding: 0;
            background: radial-gradient(#57bfc7, #45a6b3);
        }

        .container {
            display: flex;
            height: 100vh;
            align-items: center;
            justify-content: center;
        }

        .content {
            text-align: center;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="content" id="app">
        <botman-tinker api-endpoint="/botman"></botman-tinker>
    </div>
</div>

<script src="/js/app.js"></script>
</body>
</html>